openapi: 3.0.3
info:
  title: Library API
  version: 1.0.0
  description: STD22064
servers:
  - url: https://library.com
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        #TODO3: add parameter to filter books by intervals of dates of the releaseDate
        - in: query
          name: releaseDateStart
          description: Filter books released after this date
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: releaseDateEnd
          description: Filter books released before this date
          required: false
          schema:
            type: string
            format: date
      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  '/books/{bookId}/topic/{topicId}':
    put:
      tags:
        - Topics
      summary: Assigning a topic to a book
      operationId: assignTopitToBook
      parameters:
        - in: path
          name: bookId
          description: ID of the book
          required: true
          schema:
            type: string
        - in: path
          name: topicId
          description: ID of the topic
          required: true
          schema:
            type: string
      responses:
        200:
          description: topic assigned to a book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
  /books/topics:
    put:
      tags:
        - Topics
      summary: Associating books to topics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bookId:
                  type: string
                topicId:
                  type: integer
      responses:
        200:
          description: The updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    
  '/authors':
  #TODO2: complete GET (can be filtered by name) - PUT - DELETE
    get:
      tags:
        - Authors
      summary: Get all authors
      description: Get a list of all authors or filter by name.
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: Filter authors by name
          required: false
          schema:
            type: string
      responses:
        200:
          description: The list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    put:
      tags:
        - Authors
      summary: Create or update an author
      operationId: crupdateAuthor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The author has been created or updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
  '/authors/delete/{authorId}/':
    delete:  
      tags:
        - Authors
      summary: Delete an author by his ID
      operationId: deleteAuthor
      parameters:
        - in: path
          name: authorId
          description: ID of the author to delete
          required: true
          schema:
            type: string
      responses:
        200:
          description: The author has been deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
                  
components:
  schemas:
    Book:
      type: object
      properties:
        bookId:
          type: string
        bookName:
          type: string
        author:
          #TODO1: set it as a component with properties : id, name, sex (M or F)
          $ref: '#/components/schemas/Author'
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          $ref: '#/components/schemas/Author'
    sex:
      type: string
        enum:
          - M
          - F
    Topic:
      type: object
      properties:
        topicId:
          type: integer
        topicName:
          type: string